name: trident validate

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  validate:
    name: validate packages
    runs-on: ubuntu-latest
    steps:

    - name: Clone data repo
      uses: actions/checkout@v3
      with:
        path: data

    - name: Check if all files have UTF-8 encoding and Unix line endings
      run: ./checkFileEncoding.sh
      working-directory: ./data

    - name: Install trident
      run: |
        wget https://github.com/poseidon-framework/poseidon-hs/releases/latest/download/trident-Linux
        chmod +x trident-Linux

    - name: Validation
      run: ./trident-Linux validate -d data --ignoreGeno --logMode VerboseLog

    - name: Check for displaced files
      run: ./checkForDisplacedFiles.sh
      working-directory: ./data

    - name: Check if all registered files are actually LFS pointers
      run: git lfs fsck --pointers
      working-directory: ./data

    - name: Check if any .janno and .ssf files start with a single or double-quote character
      run: ./checkQuotes.sh
      working-directory: ./data
